
on:
    schedule:
    - cron: '0 17 1 * *' # Run on the 1st of every month at 4pm UTC

jobs:
  empty_commit:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3

      - run: git config user.email "megan.holtorf@gmail.com"
      - run: git config user.name "mholtorf"

      - name: Create Empty Commit
        run: git commit --allow-empty -m "Empty commit to keep running"

      - name: Push Empty Commit
        run: git push origin main  # Change 'main' to your branch name
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}